### ISSUE TITLE
Installing astra toolbox on Windows

### ISSUE THREAD

**Issue by thomasaarholt** [usnistgov/etspy#3]
Hiya! I'm just having a look at this to see if I can use it with my HAADF data.
I'm primarily on Windows, but will probably be doing reconstructions on linux (once I figure out my workflow). I noticed that conda can't resolve installing astra-toolbox on windows, unless I specify the dev label:

`conda install -c astra-toolbox/label/dev astra-toolbox`

So perhaps that could be added to the readme, unless you have any other thoughts about that. Cheers for making this repo!

**Comment by AndrewHerzing** [comment]
Sorry for the late response.  Yes, I noticed this as well.  I was hoping that Astra would refresh their conda repository so that version 1.9 would become the default, but they have not yet done this.  I will modify the installation instructions until they get around to it.

Let me know if you have any thoughts on the software.
